name: Telegram Pull Request Notifier

on:
  pull_request_target:
    types: [opened, review_requested]

jobs:
  notification:
    runs-on: ubuntu-latest

    steps:
      - name: Report
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚀 New PR in opengov registry, please review @SoloCrack

              PR: ${{ github.event.pull_request.html_url }}
